#!/bin/bash
set -e

WPROOT="/backup/whatsapp"
WPPATH="/sdcard/WhatsApp/Media/WhatsApp"

# Check if device is online and fail otherwise
adb devices

# Download all that are new
for tp in "Audio" "Video" "Images" "Documents"
do
	if [ ! -d "$WPROOT/$tp" ]
	then
		mkdir -p $WPROOT/$tp
	fi
	
	out=`adb shell "ls $WPPATH\ $tp"`
	flg=1
	echo "Checking for new files in $tp ..."
	for i in $out
	do
		if [ ! -e "$WPROOT/$tp/$i" ]
		then
			echo "New file named $i"
			adb pull "$WPPATH $tp/$i" "$WPROOT/$tp/"
			flg=0
		fi
	done
	if [ $flg ]
	then
		echo "No new files in $tp"
	fi

	echo
done

# Download all new statuses
echo "Checking for new Statuses ..."
WPSTATUS="/sdcard/WhatsApp/Media/.Statuses"

if [ ! -d "$WPSTATUS" ]
then
	mkdir -p "$WPROOT/Status"
fi

SLOC=`date "+%y/%m/%d"`

if [ ! -d "$WPSTATUS/$SLOC" ]
then
	mkdir -p "$WPROOT/Status/$SLOC"
fi


out=`adb shell "ls $WPSTATUS"`
flg=1
for i in $out
do
	if [ ! -e "$WPROOT/Status/$SLOC/$i" ]
	then
		echo "New Status named $i"
		adb pull "$WPSTATUS/$i" "$WPROOT/Status/$SLOC"
		flg=0
	fi
done
if [ $flg ]
then
	echo "No new Status"
fi

