#!/bin/bash

# Put this file in /usr/local/bin/ and do chmod +x nautilus

MYNTLS="/usr/bin/nautilus"
LPREFIX=""
UPREFIX=""

# Add all the shared file names *as they appear in your filesystem*. If there is space or "/" add "\" before it.
# Issue of one dir being prefix of other dir is fixed (in line commented ####)
declare -a d_shared_dirs=('Dinesh-Sajin-Jayalal' 'Dinesh-Jayalal' 'Samir-Dinesh-Jayalal' 'TA\ files\/Pseudorandomness\ Problem\ Sets\ 2018' 'Sagar-Dinesh-Jayalal')

# Call by dropbox to nautilus has 3 arguments. (got this from strace)
# If 3 arguments are not given, run nautilus directly. Else run our hack.
if [ $# -ne 3 ]
then
	$MYNTLS "$@"
	exit 0
fi

# Third argument to nautilus by dropbox is the filename with full path (got this from strace)
# Check if the file exists. (Assumes $3 is a file and not a folder)
if [ -e "$3" ]
then
	# Do nothing
	$MYNTLS "$@"
	exit 0
else
	# must be due to shared file issue
	newpath=$3				# save old name
	path_count=${#d_shared_dirs[@]}
	for ((i=0; i<$path_count; i++))		# search
	do
		str=${d_shared_dirs[i]}
		echo $3 | grep -i "/$str" > /dev/null		#### <-- takes care of prefix cases by adding / in search string
		if [ $? == 0 ]
		then	# match found
			lstr=${str,,}		# convert to lower case which is what dropbox does !

			# replace _1st_ occurrence in path
			newpath=`echo $3 | sed "s/$LPREFIX$lstr/$UPREFIX$str/1"` 
			xdg-open "$newpath"
			exit 0
			break			# stop search
		fi
	done
	
	# Modify the arguments to nautilus
	set -- "${@:1:2}" $newpath "${@:4}"
	$MYNTLS "$@"
	exit 0
fi
